name: Build crash ARM64 ramdump parser

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build x86_64 crash for ARM64 ramdump
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Compute date string
      run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          make gcc g++ bison flex texinfo wget patch tar zip \
          build-essential libc-dev autoconf automake \
          libncurses-dev zlib1g-dev \
          libgmp-dev libmpfr-dev libmpc-dev

    - name: Build crash for ARM64 ramdump
      run: |
        make target=ARM64 -j$(nproc) warn
        file crash
        ./crash --version || true

    - name: Compress files
      run: |
        ZIP_NAME="crash_x86_64_for_arm64_ramdump-${{ env.DATE }}.zip"
        zip -9 "${ZIP_NAME}" crash
        echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

    - name: Check if tag exists
      id: check_tag
      run: |
        git fetch --tags
        TAG_NAME="crash.arm64-ramdump.${{ env.DATE }}"
        if git rev-parse --verify --quiet "refs/tags/${TAG_NAME}" >/dev/null; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      if: steps.check_tag.outputs.exists == 'false'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: crash.arm64-ramdump.${{ env.DATE }}
        release_name: Release crash ARM64 ramdump ${{ env.DATE }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: steps.check_tag.outputs.exists == 'false'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.ZIP_NAME }}
        asset_name: ${{ env.ZIP_NAME }}
        asset_content_type: application/zip

    - name: Clean up
      run: |
        make target=ARM64 clean || true
